Create travis.yml
lirantal/aws-s3-utils pull request #5
Opened 2018-10-02 12:18 UTC by sidhyatikku

Created .travis.yml issue #3

2018-10-02 17:17 UTC, sidhyatikku commented
It looks alright 👍

2018-10-02 18:57 UTC, lirantal requested changes

2018-10-02 18:57 UTC, lirantal commented on .travis.yml
> +  - "iojs"
- `iojs` not required
- we should test 6.10, and also node 8 and 10

2018-10-02 18:57 UTC, lirantal commented on .travis.yml
> +before_install:
you don't need the manual installation of yarn because travis ci will detect the `yarn.lock` file and install it for us

2018-10-02 18:57 UTC, lirantal commented on codecov.yml
> +cat codecov.yml curl --data-binary @- https://codecov.io/validate
the codecov definition file isn't really required
we need to install it in CI and then run it after the tests finish so it reports back to codecov. you can see an example of how it is used in https://github.com/lirantal/npq/blob/master/.travis.yml as a reference

2018-10-02 18:57 UTC, lirantal commented
thanks @sidhyatikku!
those were some long awaited issues that can now be closed 🎉 

I left some comments on how to update the PR so we can merge it in

2018-10-02 19:12 UTC, sidhyatikku commented
@lirantal done ✅

2018-10-02 21:33 UTC, lirantal requested changes

2018-10-02 21:33 UTC, lirantal commented on .travis.yml
> +  - "6"
6 will fail. we need to have 6.10 specifically:
```
- "6.10.0"
```

2018-10-02 21:33 UTC, lirantal commented on .travis.yml
> +  - "7"
7 is not required as it's not relevant anymore with 8 being out and 10 kicking in soon for LTS.

2018-10-02 21:34 UTC, lirantal commented
@sidhyatikku I also enabled travis CI so we can test if the PR works correctly.

2018-10-02 21:35 UTC, lirantal requested changes

2018-10-02 21:35 UTC, lirantal commented on .travis.yml
> +sudo: enabled
not required, we can remove it.

2018-10-02 21:35 UTC, lirantal commented on .travis.yml
> +sudo: enabled
please also update travis.yml for:

```
install:
  - yarn global add codecov
script:
  - yarn run test
  - codecov
```

2018-10-04 06:01 UTC, lirantal commented
I noticed I had a wrong assumption about >= node 6.10 due to async functions in use in the library so I updated the PR to remove it, and cleaned up the before/after calls to codecov.

Looks great, thanks @sidhyatikku!

2018-10-04 06:03 UTC, merged